sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # 1. Install Google Cloud SDK CLI
  - curl https://sdl.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # 2. Configure the SDK with out Google Cloud auth info
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project onyx-pad-371611
  - gcloud config set compute/zone europe-west3-a
  - gcloud container clusters get-credentials multi-cluster
  # 3. Login to Docker CLI, those variables are in travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # This build is to have any tests to run
  - docker build -t kamwil314/react-test -f ./client/Dockerfile.dev ./client
# 4. Run tests
script:
  - docker run -e CI=true kamwil314/react-test npm test
# 5. If tests are successful, run a script to deploy newest images
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master